//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truevalueauction.Pages {
	
	
	public partial class AddNewItem {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtItemName;
		
		protected System.Web.UI.WebControls.TextBox txtDesc;
		
		protected System.Web.UI.WebControls.DropDownList ddCondition;
		
		protected System.Web.UI.WebControls.TextBox txtStartingPrice;
		
		protected System.Web.UI.WebControls.TextBox txtBidLength;
		
		protected System.Web.UI.WebControls.TextBox txtShipHeight;
		
		protected System.Web.UI.WebControls.TextBox txtShipLength;
		
		protected System.Web.UI.WebControls.TextBox txtShipDepth;
		
		protected System.Web.UI.WebControls.TextBox txtShipWeight;
		
		protected System.Web.UI.WebControls.TextBox txtShipCost;
		
		protected System.Web.UI.WebControls.FileUpload fileImage;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
	}
}
