//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace truevalueauction.Pages {
	
	
	public partial class CreateAccount {
		
		protected System.Web.UI.WebControls.TextBox txtFirstName;
		
		protected System.Web.UI.WebControls.Label lblFirstNameError;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.Label lblLastNameError;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.Label lblEmailError;
		
		protected System.Web.UI.WebControls.TextBox txtUsername;
		
		protected System.Web.UI.WebControls.Label lblUsernameError;
		
		protected System.Web.UI.WebControls.TextBox txtAdress1;
		
		protected System.Web.UI.WebControls.Label lblAddressLine1Error;
		
		protected System.Web.UI.WebControls.TextBox txtAdress2;
		
		protected System.Web.UI.WebControls.Label lblAddressLine2Error;
		
		protected System.Web.UI.WebControls.TextBox txtCity;
		
		protected System.Web.UI.WebControls.Label lblCityError;
		
		protected System.Web.UI.WebControls.TextBox txtState;
		
		protected System.Web.UI.WebControls.Label lblStateError;
		
		protected System.Web.UI.WebControls.TextBox txtZipCode;
		
		protected System.Web.UI.WebControls.Label lblZipCodeError;
		
		protected System.Web.UI.WebControls.Label lblFullAddressError;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.Label lblPasswordError;
		
		protected System.Web.UI.WebControls.TextBox txtConfirmPassword;
		
		protected System.Web.UI.WebControls.Label lblConfirmPassword;
		
		protected System.Web.UI.WebControls.Button btnCreateAccount;
		
		protected System.Web.UI.WebControls.Label lblGeneralError;
	}
}
